### ISSUE TITLE
Help: Using recrypt-wasm-binding with Create-React-App

### ISSUE THREAD

**Issue by dghelm** [IronCoreLabs/recrypt-wasm-binding#85]
I found the webpack-usage documentation somewhat confusing, even after trying to eject a create-react-app project. I'm new to wasm+react, but was hoping using the npm module would make it more seamless.

Would love any additional documentation for using this in client-side browser applications.

**Comment by skeet70** [comment]
I'm not very familiar with `create-react-app` but using the npm module makes it as seamless as it can be. All of the documentation is targeted at using this client side. Is there any step you're struggling with in particular? We may be able to help but "more documentation" is a bit vague.

From your mention of webpack it seems like the part you're struggling with may be getting the wasm into your bundle and imported? It's hard to have specific documentation on that because it's not a peculiarity of our library, it's a general issue for any wasm use from Javascript. The specifics of how to make it work are up to your chosen building and bundling system.

I dug into it a bit and added an [example](https://github.com/IronCoreLabs/recrypt-wasm-binding/tree/create-react-app-example/examples/create-react-app-example) to the repo that hopefully helps clarify things for you a bit. It's on a branch right now but will go into `main` in #86.

**Comment by dghelm** [comment]
Sorry for the vagues request, but this is above and beyond exactly what I needed to get the library working in my react app.

Thank you so much for taking the time!
